---
# defaults file for searxng

# renovate: datasource=docker depName=searxng/searxng versioning=loose
searxng_docker_image: searxng/searxng:2025.12.26-fc6e59d3e@sha256:74c9ee6120b2c990999fcbe14b69b0dbb981bfbd70b2f2cf63b2c094f11bc883

searxng_secret_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36366337306131306631376364393764656438363661616564316339303831626566356263346263
  3265343033363030616464666133353231616564346663370a623734636139393039316239313066
  39356131333837633635373832396531386566373933396635353033346665353933653964643135
  3764323164386130390a343537646134663239656639376166313030383066323235663136343233
  39363661383037633339353564343032343663343838663733613265383331363233333734666132
  32653234326237633264643436323431663038353962303465356336623033303835363130383662
  63323564333263636339316536636135616634353166313937613562666630373032333734613064
  65653830326639326132
